### ISSUE TITLE
auto walls work on a20 too!

### ISSUE THREAD

**Issue by Gussak** [stallionsden/Valmars-A21-Mods#1]
I found that just fixing the ModInfo.xml, it works on a20 too! just put all cfg inside \<ModInfo\>... and comment the \<DisplayName\>. (requires closing and rerunning the game application tho).
I am wating for a22 before updating my mods, so I play still on a20.

thx!

**Comment by Gussak** [comment]
thx!

**Comment by stallionsden** [comment]
Hi

Yes I will be getting to the mods shortly and fix properly appreciate the
feedback thank you hopefully most just need modinfo fixed
